[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.flash_mode = dio
upload_speed = 921600

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43

; Говорим PlatformIO использовать наш User_Setup.h из корня проекта
build_flags = 
    -DUSER_SETUP_LOADED=1
    -I .
